//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "file")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
    pub path: String,
    pub file_size: String,
    pub file_type_id: i64,
    #[sea_orm(
        belongs_to,
        from = "file_type_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub file_type: HasOne<super::file_type::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
