//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "storage_root")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
    pub mount_path: String,
    pub volume_uuid: Option<String>,
    #[sea_orm(has_many)]
    pub files: HasMany<super::file::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
